# Generated by Django 4.2.5 on 2023-11-02 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_advertisements', '0003_advertisement_user_alter_advertisement_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='image',
            field=models.ImageField(default=' ', upload_to='advertisements', verbose_name='Изображение'),
            preserve_default=False,
        ),
    ]
